project:
  type: website
  output-dir: docs

website:
  title: "Koh Zhi Rong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: data-visualization.qmd
        text: Data Visualization
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true